[project]
name = "podtuber"
version = "0.1.1"
description = "Create podcast .rss files from YouTube playlists"
authors = [{ name = "Zvika Haramaty", email = "haramaty.zvika@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "podgen>=1.1.0",
    "pytube>=15.0.0",
    "pathvalidate>=3.1.0",
    "tomli>=2.0.1",
    "pytz",
]

[project.urls]
Repository = "https://github.com/ZvikaZ/podtuber"

[project.scripts]
podtuber = "podtuber.main:main"

[dependency-groups]
dev = [
    "getpodcast>=1.0.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
